#!/bin/bash
# find updater | entr ./updater

prev_version=$(jq -r '.version' ./package.json)
new_version=$(awk '
  BEGIN{FS=".";OFS="."}
  {print $1, $2, $3+1}
' <(echo $prev_version))


echo "*** new_version: $new_version"

new_package_file=$(awk \
  -v prev_version="$prev_version" \
  -v new_version="$new_version" \
  '{
    gsub(prev_version, new_version, $0);
    print $0;
  }' ./package.json
)



echo "*** new_package_file:"
echo $new_package_file | jq . > ./package.json

echo "console.log('*** Latest Ver. Number: $new_version');" >> ./main.js

echo -e '\n*********** END ***********\n'

git add ./main.js ./package.json
git commit -m "'[updater] $new_version'"
git push
